### ISSUE TITLE
ng2-facebook-sdk version 2.0.0

### ISSUE THREAD

**Issue by ihadeed** [zyra/ng2-facebook-sdk#53]
Currently working on version `2.0.0` of this module. The work is being done in the `v2` branch.

# What's changing?
- Interfaces no longer have `Facebook` prefix. Example: `FacebookLoginOptions` is now `LoginOptions`
- `UiParams` and `UiResponse` are now `UIParams` and `UIResponse`.
- Adding components to make using [Facebook Plugins](https://developers.facebook.com/docs/plugins) easier

# What needs to change in your application?
You just need to refactor any interface usage to work with the changes mentioned above.

If you want to use the components in your app, you need to do 2 things:
- Remove `FacebookService` and add `FacebookModule` in your `NgModule`
- Use the following link in your script tag, you can change the language or use a later version: `//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.8`

# How can I use this in my app now?
```
npm i --save ng2-facebook-sdk@next
```

# To-do
- [X] Export NgModule
- [x] Comments
- [x] Embedded comments
- [x] Embedded posts
- [x] Embedded videos
- [X] Follow button
- [X] Like button
- [X] Page plugin
- [x] Quote plugin
- [x] Save button
- [x] Send button
- [x] Share button
- [x] Complete documentation
- [x] Complete testing
- [x] Event listeners

**Comment by AsmaGargouri** [comment]
Hello, thank you for your work. 

I am just getting error when I updated to v2.0.0, after doing an npm install, and then updated the ngModule and my Component. 

The error is saying : 
GET http://localhost:3000/node_modules/ng2-facebook-sdk/dist/components.js 

I didn't change the ts.config.js and I don't know if I have to do it. 
Thank you

**Comment by ihadeed** [comment]
@AsmaGargouri 

Could you please share a minimal project that produces this issue? 

Your system.js config seems correct. Make sure you also have ` 'ng2-facebook-sdk': 'npm:ng2-facebook-sdk'` under `map`.

I personally use angular-cli to serve/build my Angular 2 applications. As demonstrated here: https://github.com/zyramedia/ng2-facebook-sdk-example/

**Comment by AsmaGargouri** [comment]
@ihadeed , yes I do have 'ng2-facebook-sdk': 'npm:ng2-facebook-sdk' under map. 
I have returned to 1.2 for the moment.

I will try to reproduce the issue later. Thank you

**Comment by Benratelade** [comment]
I am having pretty much the same error. 
I noticed in the latest version, the file tree is quite different: 
![package_json_ _angular-brewbros](https://cloud.githubusercontent.com/assets/8875705/25064039/82b7e1ee-2235-11e7-997c-ec6686159500.png)
![package_json_ _angular-brewbros](https://cloud.githubusercontent.com/assets/8875705/25064043/94208d14-2235-11e7-8626-088fa8359e9b.png)
Notice that dist has 2 subfolders: esm and umd. index.js is in those subfolders, so the path that AsmaGargouri was pointing to in his system.js.config was probably incorrect. 

However, even by pointing to one of the subfolders, I keep getting 404 errors, but for Traceur this time. 

Not too sure how to fix it.

**Comment by ihadeed** [comment]
@Benratelade the error that AsmaGargouri was getting was caused by some beta issues. This new structure solves these problems. 

SystemJS uses the `umd` module as it's plain `ES5` instead of the `ES2015` module in the `esm` directory.
