### ISSUE TITLE
Error TypeError: t is not a function

### ISSUE THREAD

**Issue by randomdude3512** [zyra/ng2-facebook-sdk#70]
I was just trying to make a Facebook login. But the following error is showing. I am attaching the screenshot of the error. both in safari and chrome.
In chrome
<img width="1280" alt="screen shot 2017-04-11 at 11 57 38 pm" src="https://cloud.githubusercontent.com/assets/27009430/24923371/2275971a-1f13-11e7-9ff8-de9280eaecc1.png">
In safari
<img width="1280" alt="screen shot 2017-04-11 at 11 57 16 pm" src="https://cloud.githubusercontent.com/assets/27009430/24923380/2bf07a4e-1f13-11e7-92c6-26051fe36724.png">
at `line 8727` the value of `w` is like returning an `authResponse` object.
<img width="1280" alt="screen shot 2017-04-11 at 11 57 24 pm" src="https://cloud.githubusercontent.com/assets/27009430/24923382/2c498828-1f13-11e7-9dcd-a18a23f94ef7.png">

My Facebook login component is like this
`
export class FacebookLoginComponent implements OnInit {

    constructor(private fb: FacebookService) {
        const initParams: InitParams = {
            appId: Config.facebook_api_id,
            xfbml: true,
            version: 'v2.8'
        };

        this.fb.init(initParams);
    }

    ngOnInit() {

    }

    loginWithFacebook(): void {
        this.fb.login({scope: 'email, public_profile'})
            .then(
                (response: LoginResponse) => {
                    console.log(response);
                }
            )
            .catch((error: any) => console.error(error));

    }
}
`
Need help.TIA

**Comment by ihadeed** [comment]
This looks like an issue caused by the Facebook SDK and not by this library. Try using a different version of the SDK?

Also, check if you have any browser extensions installed that might be blocking parts of the SDK.
